<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MS-LAP-02" name="com.SigmaInbound.Sigmaoutbound" tests="15" failures="1" timestamp="19 Jun 2020 09:04:51 GMT" time="1137.794" errors="0">
  <testcase name="account" time="75.383" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="shipment" time="80.084" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="Payment" time="83.651" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="Package" time="77.470" classname="com.SigmaInbound.Sigmaoutbound">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at com.SigmaInbound.Sigmaoutbound.Package(Sigmaoutbound.java:1360)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Package -->
  <testcase name="VendorContact" time="65.935" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="sigmaorder" time="68.837" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="stockreceive" time="154.307" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="Cashcustomer" time="121.409" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="sigmaordersave" time="10.179" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="purchaseorder" time="84.005" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="picking" time="83.242" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="Aallocation" time="33.724" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="product" time="89.836" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="CustomerContact" time="68.395" classname="com.SigmaInbound.Sigmaoutbound"/>
  <testcase name="sigmaorderline" time="41.337" classname="com.SigmaInbound.Sigmaoutbound"/>
</testsuite> <!-- com.SigmaInbound.Sigmaoutbound -->
